spring:
  application:
    name: cloud-service-bbb

server:
  port: ${PORT:${SERVER_PORT:9002}}

eureka:
  client:
    serviceUrl:
      defaultZone: http://user:password@localhost:8761/eureka/

logging:
  level:
    com:
      uvanix: debug
