spring:
  application:
    name: cloud-service-bbb
  profiles:
    active: dev
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  cloud:
    inetutils:
      use-only-site-local-interfaces: true
    loadbalancer:
      retry:
        enabled: true
server:
  port: ${PORT:7002}
  session:
    timeout: 60
logging:
  config: classpath:config/logback-config.xml
  file: logs/cloud-service-bbb.log
  level:
    org:
      springframework:
        transaction: debug
      mybatis: debug
    com:
      uvanix:
        cloud: debug
management:
  context-path: /mgmt
  security:
    enabled: false
info:
  app:
    name: "@project.name@"
    description: "@project.description@"
    version: "@project.version@"
feign:
  hystrix:
    enabled: true
ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 3000
  MaxAutoRetries: 1 # 同一台实例的最大重试次数,不包括首次调用
  MaxAutoRetriesNextServer: 2 # 重试负载均衡其他实例的最大重试次数,不包括首次实例
  OkToRetryOnAllOperations: false # 是否所有的操作都重试
hystrix:
  command:
    default:
      circuitBreaker:
        requestVolumeThreshold: 100 # 一个rolling window内最小的请求数
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 36000 # hystrixTimeout = (commandRibbonConnectTimeout + commandRibbonReadTimeout) x (commandRibbonMaxAutoRetries + 1) x (commandRibbonMaxAutoRetriesNextServer + 1)

# 开发环境 use command to startup [ nohup mvn clean spring-boot:run > /dev/null 2>&1 & ]
---
spring:
  profiles: dev
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    enabled: true
    sampler:
      percentage: 1.0 # 采样率 0.0 ～ 0.1
eureka:
  instance:
    hostname: ${spring.application.name}
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    status-page-url: http://${spring.cloud.client.ipAddress}:${server.port}${management.context-path}${endpoints.info.path:/info}
    health-check-url-path: http://${spring.cloud.client.ipAddress}:${server.port}${management.context-path}${endpoints.info.path:/health}
    metadata-map:
      management.context-path: ${management.context-path}
      user.name: ${security.user.name}
      user.password: ${security.user.password}
    leaseRenewalIntervalInSeconds: 5
    lease-expiration-duration-in-seconds: 15
  client:
    health:
      enabled: true
    serviceUrl:
      defaultZone: http://user:password@localhost:8761/eureka/
    registryFetchIntervalSeconds: 5
