spring:
  application:
    name: cloud-config-server
  profiles:
    active: dev
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  cloud:
    inetutils:
      use-only-site-local-interfaces: true
    config:
      server:
        git:
          uri: https://github.com/uvanix/spring-cloud-microservice-demo
          search-paths: config-repo
          username:
          password:
server:
  port: ${PORT:8666}
  session:
    timeout: 60
  tomcat:
    max-threads: 800
    uri-encoding: UTF-8
    basedir: logs
logging:
  config: classpath:config/logback-config.xml
  file: logs/cloud-config-server.log
management:
  security:
    enabled: false
  context-path: /mgmt
info:
  app:
    name: "@project.name@"
    description: "@project.description@"
    version: "@project.version@"

# 开发环境 use command to startup [ nohup mvn clean spring-boot:run > /dev/null 2>&1 & ]
---
spring:
  profiles: dev
eureka:
  instance:
    hostname: ${spring.application.name}
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    status-page-url: http://${spring.cloud.client.ipAddress}:${server.port}${management.context-path}${endpoints.info.path:/info}
    health-check-url-path: http://${spring.cloud.client.ipAddress}:${server.port}${management.context-path}${endpoints.info.path:/health}
    metadata-map:
      management.context-path: ${management.context-path}
    leaseRenewalIntervalInSeconds: 5
    lease-expiration-duration-in-seconds: 15
  client:
    health:
      enabled: true
    serviceUrl:
      defaultZone: http://user:password@localhost:8761/eureka/
    registryFetchIntervalSeconds: 5
