spring:
  application:
    name: 'cloud-config-server'
  cloud:
    config:
      server:
        git:
          uri: https://github.com/uvanix/spring-cloud-microservice-demo
          search-paths: config-repo

server:
  port: ${PORT:${SERVER_PORT:8888}}

logging:
  level:
    com:
      uvanix:
        cloud: 'debug'

security:
  user:
    name: user
    password: ${REGISTRY_SERVER_PASSWORD:password}
