spring:
  application:
    name: cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/uvanix/spring-cloud-microservice-demo
          search-paths: config-repo

server:
  port: ${PORT:${SERVER_PORT:9999}}

security:
  user:
    name: user
    password: ${PASSWORD:password}
