spring:
  application:
    name: cloud-zuul-apigateway
  profiles:
    active: dev
  zipkin:
    base-url: http://localhost:8666
  sleuth:
    sampler:
      # 采样率 0.0 ～ 0.1
      percentage: 1.0

server:
  port: ${PORT:${SERVER_PORT:8888}}

# routes to serviceId
zuul:
  routes:
    api-aaa:
      path: /cloud-service-aaa/**
      serviceId: cloud-service-aaa
    api-bbb:
      path: /cloud-service-bbb/**
      serviceId: cloud-service-bbb

eureka:
  client:
    serviceUrl:
      defaultZone: http://user:password@localhost:8761/eureka/

turbine:
#  instanceUrlSuffix: /hystrix/hystrix.stream
  # 配置Eureka中的serviceId列表，表明监控哪些服务
  app-config: cloud-zuul-apigateway,cloud-service-aaa,cloud-service-bbb
  # 指定聚合哪些集群，多个使用”,”分割，默认为default。可使用http://.../turbine.stream?cluster={clusterConfig之一}访问
  aggregator:
    cluster-config: default
  cluster-name-expression: new String("default")
