spring:
  application:
    name: cloud-admin-server
  profiles:
    active: dev
  cloud:
    inetutils:
      use-only-site-local-interfaces: true
server:
  port: ${PORT:9410}
logging:
  config: classpath:config/logback-config.xml
  file: logs/cloud-admin-server.log
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: when_authorized
info:
  app:
    name: "@project.name@"
    description: "@project.description@"
    version: "@project.version@"

# 开发环境 use command to startup [ nohup mvn clean spring-boot:run > /dev/null 2>&1 & ]
---
spring:
  profiles: dev
  security:
    user:
      name: user
      password: password
eureka:
  instance:
    hostname: ${spring.application.name}
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    home-page-url-path: http://${spring.cloud.client.ip-address}:${server.port}/actuator
    status-page-url: ${eureka.instance.home-page-url-path}/info
    health-check-url-path: ${eureka.instance.home-page-url-path}/health
    metadata-map:
      user.name: ${spring.security.user.name}
      user.password: ${spring.security.user.password}
    leaseRenewalIntervalInSeconds: 5
    lease-expiration-duration-in-seconds: 15
  client:
    health:
      enabled: true
    serviceUrl:
      defaultZone: http://user:password@localhost:8761/eureka/
#      defaultZone: http://user:password@localhost:8001/eureka/,http://user:password@localhost:8002/eureka/,http://user:password@localhost:8003/eureka/
    registryFetchIntervalSeconds: 5
