spring:
  application:
    name: cloud-admin-server
  profiles:
    active: dev
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  boot:
    admin:
      discovery:
        converter.management-context-path: /mgmt
      routes:
        endpoints: env,metrics,dump,jolokia,info,configprops,trace,logfile,refresh,heapdump,loggers,auditevents,hystrix.stream,turbine.stream,activiti
      turbine:
        location: ${spring.application.name}
  cloud:
    inetutils:
      use-only-site-local-interfaces: true
server:
  port: ${PORT:9410}
  session:
    timeout: 60
  tomcat:
    max-threads: 800
    uri-encoding: UTF-8
    basedir: logs
logging:
  config: classpath:config/logback-config.xml
  file: logs/cloud-admin-server.log
security:
  user:
    name: user
    password: password
management:
  context-path: /mgmt
info:
  app:
    name: "@project.name@"
    description: "@project.description@"
    version: "@project.version@"
turbine:
  # 配置Eureka中的serviceId列表，表明监控哪些服务
  app-config: cloud-zuul-gateway,cloud-service-bbb

# 开发环境 use command to startup [ nohup mvn clean spring-boot:run > /dev/null 2>&1 & ]
---
spring:
  profiles: dev
eureka:
  instance:
    hostname: ${spring.application.name}
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    status-page-url: http://${spring.cloud.client.ipAddress}:${server.port}${management.context-path}${endpoints.info.path:/info}
    health-check-url-path: http://${spring.cloud.client.ipAddress}:${server.port}${management.context-path}${endpoints.info.path:/health}
    metadata-map:
      management.context-path: ${management.context-path}
      user.name: ${security.user.name}
      user.password: ${security.user.password}
    leaseRenewalIntervalInSeconds: 5
    lease-expiration-duration-in-seconds: 15
  client:
    health:
      enabled: true
    serviceUrl:
      defaultZone: http://user:password@localhost:8761/eureka/
    registryFetchIntervalSeconds: 5
