spring:
  application:
    name: cloud-service-aaa
  profiles:
    active: dev
  cloud:
    inetutils:
      use-only-site-local-interfaces: true
server:
  port: ${PORT:7001}
logging:
  config: classpath:config/logback-config.xml
  file: logs/cloud-service-aaa.log
  level:
    org:
      springframework:
        transaction: debug
      mybatis: debug
    com:
      uvanix:
        cloud: debug
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
info:
  app:
    name: "@project.name@"
    description: "@project.description@"
    version: "@project.version@"

# 开发环境 use command to startup [ nohup mvn clean spring-boot:run > /dev/null 2>&1 & ]
---
spring:
  profiles: dev
eureka:
  instance:
    hostname: ${spring.application.name}
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    home-page-url-path: http://${spring.cloud.client.ip-address}:${server.port}/actuator
    status-page-url: ${eureka.instance.home-page-url-path}/info
    health-check-url-path: ${eureka.instance.home-page-url-path}/health
    leaseRenewalIntervalInSeconds: 5
    lease-expiration-duration-in-seconds: 15
  client:
    health:
      enabled: true
    serviceUrl:
      defaultZone: http://user:password@localhost:8761/eureka/
    registryFetchIntervalSeconds: 5
