# 公共配置
spring:
  application:
    name: cloud-eureka-server
  profiles:
    active: dev

server:
  port: ${PORT:${SERVER_PORT:8761}}

eureka:
  server:
    # 关闭保护机制，以确保注册中心可以将不可用的实例剔除.
    # 注意：自我保护模式是一种应对网络异常的安全保护措施,使用自我保护模式，可以让Eureka集群更加的健壮、稳定
    enable-self-preservation: true
    # #eureka server清理无效节点的时间间隔，默认60000毫秒，即60秒
    eviction-interval-timer-in-ms: 30000

security:
  user:
    name: user
    password: ${REGISTRY_SERVER_PASSWORD:password}

# 用---分割不同的环境对应的配置信息（YML以"---"作为文档分割符，以"..."作为结束标志）
---
spring:
  profiles: dev

eureka:
  client:
    # 设置是否从注册中心获取注册信息（缺省true）
    # 因为这是一个单点的EurekaServer，不需要同步其它EurekaServer节点的数据，故设为false
    fetch-registry: false
    # 设置是否将自己作为客户端注册到注册中心（缺省true）
    register-with-eureka: false
    serviceUrl:
      defaultZone: http://localhost:${server.port}/eureka/

---
spring:
  profiles: node1

eureka:
  instance:
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:${server.port:8761}/eureka/

---
spring:
  profiles: node2

eureka:
  instance:
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:${server.port:8761}/eureka/
