spring:
  application:
    name: cloud-eureka-server
  profiles:
    active: dev
  cloud:
    inetutils:
      use-only-site-local-interfaces: true
server:
  port: ${PORT:8761}
logging:
  config: classpath:config/logback-config.xml
  file: logs/cloud-eureka-server.log
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: when_authorized
info:
  app:
    name: "@project.name@"
    description: "@project.description@"
    version: "@project.version@"

# 单节点 use command to startup [ nohup mvn clean spring-boot:run > /dev/null 2>&1 & ]
---
spring:
  profiles: dev
  security:
    user:
      name: user
      password: password
eureka:
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 5000
  instance:
    hostname: localhost
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    home-page-url-path: http://${spring.cloud.client.ip-address}:${server.port}/actuator
    status-page-url: ${eureka.instance.home-page-url-path}/info
    health-check-url-path: ${eureka.instance.home-page-url-path}/health
    metadata-map:
      user.name: ${spring.security.user.name}
      user.password: ${spring.security.user.password}
    leaseRenewalIntervalInSeconds: 5
    lease-expiration-duration-in-seconds: 15
  client:
    # 设置是否从注册中心获取注册信息（缺省true）
    # 因为这是一个单点的EurekaServer，不需要同步其它EurekaServer节点的数据，故设为false
    fetch-registry: false
    # 设置是否将自己作为客户端注册到注册中心（缺省true）
    register-with-eureka: false
    serviceUrl:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:${server.port}/eureka/

# 本机集群需配置host 127.0.0.1 peer1 127.0.0.1 peer2 127.0.0.1 peer3
# 集群节点1 use command to startup [ mvn spring-boot:run -Dspring.profiles.active=peer1 ]
---
spring:
  profiles: peer1
  security:
    user:
      name: user
      password: password
server:
  port: ${PORT:8001}
eureka:
  instance:
    hostname: ${spring.profiles}
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    home-page-url-path: http://${spring.cloud.client.ip-address}:${server.port}/actuator
    status-page-url: ${eureka.instance.home-page-url-path}/info
    health-check-url-path: ${eureka.instance.home-page-url-path}/health
    metadata-map:
      user.name: ${spring.security.user.name}
      user.password: ${spring.security.user.password}
  client:
    serviceUrl:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@peer2:8002/eureka/,http://${spring.security.user.name}:${spring.security.user.password}@peer3:8003/eureka/

# 集群节点2 use command to startup [ mvn spring-boot:run -Dspring.profiles.active=peer2 ]
---
spring:
  profiles: peer2
  security:
    user:
      name: user
      password: password
server:
  port: ${PORT:8002}
eureka:
  instance:
    hostname: ${spring.profiles}
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    home-page-url-path: http://${spring.cloud.client.ip-address}:${server.port}/actuator
    status-page-url: ${eureka.instance.home-page-url-path}/info
    health-check-url-path: ${eureka.instance.home-page-url-path}/health
    metadata-map:
      user.name: ${spring.security.user.name}
      user.password: ${spring.security.user.password}
  client:
    serviceUrl:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@peer1:8001/eureka/,http://${spring.security.user.name}:${spring.security.user.password}@peer3:8003/eureka/

# 集群节点3 use command to startup [ mvn spring-boot:run -Dspring.profiles.active=peer3 ]
---
spring:
  profiles: peer3
  security:
    user:
      name: user
      password: password
server:
  port: ${PORT:8003}
eureka:
  instance:
    hostname: ${spring.profiles}
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    home-page-url-path: http://${spring.cloud.client.ip-address}:${server.port}/actuator
    status-page-url: ${eureka.instance.home-page-url-path}/info
    health-check-url-path: ${eureka.instance.home-page-url-path}/health
    metadata-map:
      user.name: ${spring.security.user.name}
      user.password: ${spring.security.user.password}
  client:
    serviceUrl:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@peer1:8001/eureka/,http://${spring.security.user.name}:${spring.security.user.password}@peer2:8002/eureka/
