spring:
  application:
    name: cloud-eureka-server

server:
  port: ${PORT:${SERVER_PORT:8761}}

eureka:
  instance:
    hostname: localhost
  client:
    # 设置是否从注册中心获取注册信息（缺省true）
    # 因为这是一个单点的EurekaServer，不需要同步其它EurekaServer节点的数据，故设为false
    fetch-registry: false
    # 设置是否将自己作为客户端注册到注册中心（缺省true）
    register-with-eureka: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

security:
  user:
    name: user
    password: ${REGISTRY_SERVER_PASSWORD:password}
