spring:
  application:
    name: cloud-service-consul
  profiles:
    active: dev
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  cloud:
    inetutils:
      use-only-site-local-interfaces: true
    consul:
      discovery:
        health-check-path: ${management.context-path}/health
server:
  port: ${PORT:7003}
  session:
    timeout: 60
  tomcat:
    max-threads: 800
    uri-encoding: UTF-8
    basedir: logs
logging:
  config: classpath:config/logback-config.xml
  file: logs/cloud-service-consul.log
  level:
    org:
      springframework:
        transaction: debug
      mybatis: debug
    com:
      uvanix:
        cloud: debug
management:
  context-path: /mgmt
  security:
    enabled: false
info:
  app:
    name: "@project.name@"
    description: "@project.description@"
    version: "@project.version@"

# 单节点 use command to startup [ nohup mvn clean spring-boot:run > /dev/null 2>&1 & ]
---
spring:
  profiles: dev
  cloud:
    consul:
      host: localhost
      port: 8500
